name: Order Service

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create application.yml
        run: |
          mkdir -p ./order-service/src/main/resources
          echo "${{ secrets.APPLICATION_ORDR }}" | base64 --decode > ./order-service/src/main/resources/application.yml
      
      - name: Build with Gradle
        run: |
          cd order-service
          ./gradlew build -x test

      - name: Docker build
        run: |
          cd order-service
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/order-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_KEY_ORDR }} # EC2 인스턴스 퍼블릭 DNS
          username: ${{ secrets.USERNAME }} # EC2 유저내임
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker stop $(docker ps -a -q)
            docker run -d --log-driver=syslog -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f
